---
clone:
  depth: 1
kind: pipeline
type: docker
name: FoxKernel-ysl
steps:
- name: FoxKernel-ysl
  image: panchajanya1999/archlinux:latest
  environment:
  Apibot:
    from_secret: Apibot
  CHATID:
    from_secret: CHATID
  commands:
  - "curl https://raw.githubusercontent.com/Fox-kernel/myscripts/master/ysl-nonoc.sh | bash"
